apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-build: app-build
spec:
  containers:
  - name: kaniko
    image: harbor.zilliz.cc/kaniko-project/executor:v1.7.0-debug
    imagePullPolicy: IfNotPresent
    command:
    - /busybox/cat
    tty: true